model:
    learning_rate: .0007
    learning_rate_schedule_factor: .5

    # model hyperparameters
    h_dims: [64,64,64,64,64]
    h_dim_groups: 4
    convnext_mult: 2
    wave_stack_depth: 5
    wave_num_stacks: 3
    n_embed: 8192