model:
    learning_rate: .001
    learning_rate_schedule_factor: .5

    # model hyperparameters
    h_dim: 32
    h_dim_groups: 1
    dim_mults: [1,2,4,8,16]
    convnext_mult: 2
    wave_stack_depth: 5
    wave_num_stacks: 5
    timesteps: 1024
    
    # number of steps to use for sampling during validation
    sample_steps: 80

    # loss function - can be one of {huber, l1, l2}
    loss_type: "huber"
    
    # how often the timing signal should be omitted from training
    timing_dropout: .6